l = input ("What is the length of the prism? ")
w = input ("What is the width of the prism? ")
h = input ("What is the height of the prism? ")
l = int (l)
w = int (w)
h = int (h)
print("The prism is",l*w*h, "units cubed.")
